# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8"
    
# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - npm install -g typescript@2.7.2
# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run build
  - tsc --version
  #- cmd: set path="C:\projects\mmis-management-backend\node_modules\typescript\bin";%PATH%
  - cmd: tsc -p %APPVEYOR_BUILD_FOLDER%

# Don't actually build.
build: off
